namespace NetflixNext.Common.Models
{
    public class Genre
    {
        public int[] AllAction { get; set; }
        public int[] AllAnime { get; set; }
        public int[] AllChildrens { get; set; }
        public int[] AllClassics { get; set; }
        public int[] AllComedies { get; set; }
        public int[] AllCult { get; set; }
        public int[] AllDocumentaries { get; set; }
        public int[] AllDramas { get; set; }
        public int[] AllFaithandSpirituality { get; set; }
        public int[] AllGayandLesbian { get; set; }
        public int[] AllHorror { get; set; }
        public int[] AllIndependent { get; set; }
        public int[] AllInternational { get; set; }
        public int[] AllMusic { get; set; }
        public int[] AllMusicals { get; set; }
        public int[] AllRomance { get; set; }
        public int[] AllSciFi { get; set; }
        public int[] AllSports { get; set; }
        public int[] AllThrillers { get; set; }
        public int[] _20thCenturyPeriodPieces { get; set; }
        public int[] AcademyAwardWinningFilms { get; set; }
        public int[] Action { get; set; }
        public int[] ActionampAdventure { get; set; }
        public int[] ActionComedies { get; set; }
        public int[] ActionSciFiampFantasy { get; set; }
        public int[] ActionThrillers { get; set; }
        public int[] AdultAnimation { get; set; }
        public int[] Adventures { get; set; }
        public int[] AfricanMovies { get; set; }
        public int[] AfricanMusic { get; set; }
        public int[] AfricanAmericanComedies { get; set; }
        public int[] AfricanAmericanDramas { get; set; }
        public int[] AfricanAmericanStandupComedy { get; set; }
        public int[] AfroCubanampLatinJazz { get; set; }
        public int[] AlienSciFi { get; set; }
        public int[] AmericanFolkampBluegrass { get; set; }
        public int[] AnimalTales { get; set; }
        public int[] AnimalsampNatureRealityTV { get; set; }
        public int[] Anime { get; set; }
        public int[] AnimeAction { get; set; }
        public int[] AnimeComedies { get; set; }
        public int[] AnimeDramas { get; set; }
        public int[] AnimeFantasy { get; set; }
        public int[] AnimeFeatures { get; set; }
        public int[] AnimeHorror { get; set; }
        public int[] AnimeSciFi { get; set; }
        public int[] AnimeSciFiampFantasy { get; set; }
        public int[] AnimeSeries { get; set; }
        public int[] ArgentinianDramas { get; set; }
        public int[] ArgentinianFilms { get; set; }
        public int[] ArgentinianTVShows { get; set; }
        public int[] ArtHouseMovies { get; set; }
        public int[] AsianActionMovies { get; set; }
        public int[] AsianMovies { get; set; }
        public int[] AustralianComedies { get; set; }
        public int[] AustralianCrimeFilms { get; set; }
        public int[] AustralianDramas { get; set; }
        public int[] AustralianMovies { get; set; }
        public int[] AustralianThrillers { get; set; }
        public int[] AustralianTVProgrammes { get; set; }
        public int[] AwardwinningDramas { get; set; }
        public int[] AwardwinningMovies { get; set; }
        public int[] BHorrorMovies { get; set; }
        public int[] BAFTAAwardWinningFilms { get; set; }
        public int[] BaseballMovies { get; set; }
        public int[] BasketballMovies { get; set; }
        public int[] BelgianMovies { get; set; }
        public int[] BerlinFilmFestivalAwardwinningMovies { get; set; }
        public int[] BiographicalDocumentaries { get; set; }
        public int[] BiographicalDramas { get; set; }
        public int[] BlockbusterMovies { get; set; }
        public int[] BluecollarStandupComedy { get; set; }
        public int[] BollywoodFilms { get; set; }
        public int[] BoxingMovies { get; set; }
        public int[] BrazilianComedies { get; set; }
        public int[] BrazilianDocumentaries { get; set; }
        public int[] BrazilianDramas { get; set; }
        public int[] BrazilianFilms { get; set; }
        public int[] BrazilianMusicampMusicals { get; set; }
        public int[] BrazilianMusicandConcertMovies { get; set; }
        public int[] BrazilianTVShows { get; set; }
        public int[] BritishComedies { get; set; }
        public int[] BritishCrimeFilms { get; set; }
        public int[] BritishDramas { get; set; }
        public int[] BritishMiniseries { get; set; }
        public int[] BritishMovies { get; set; }
        public int[] BritishPeriodPieces { get; set; }
        public int[] BritishThrillers { get; set; }
        public int[] BritishTVComedies { get; set; }
        public int[] BritishTVDramas { get; set; }
        public int[] BritishTVMysteries { get; set; }
        public int[] BritishTVShows { get; set; }
        public int[] BritishTVSketchComedies { get; set; }
        public int[] CampyMovies { get; set; }
        public int[] CanadianComedies { get; set; }
        public int[] CanadianDocumentaries { get; set; }
        public int[] CanadianDramas { get; set; }
        public int[] CanadianFilms { get; set; }
        public int[] CanadianFrenchLanguageMovies { get; set; }
        public int[] CanadianIndependentFilms { get; set; }
        public int[] CanadianTVProgrammes { get; set; }
        public int[] CannesFilmFestivalAwardwinningMovies { get; set; }
        public int[] CannesFilmFestivalWinners { get; set; }
        public int[] CeacutesarAwardwinningMovies { get; set; }
        public int[] ChildrenampFamilyMovies { get; set; }
        public int[] ChineseMovies { get; set; }
        public int[] ClassicActionampAdventure { get; set; }
        public int[] ClassicBritishFilms { get; set; }
        public int[] ClassicChildrenampFamilyFilms { get; set; }
        public int[] ClassicComedies { get; set; }
        public int[] ClassicCountryampWestern { get; set; }
        public int[] ClassicDramas { get; set; }
        public int[] ClassicForeignMovies { get; set; }
        public int[] ClassicHorrorFilms { get; set; }
        public int[] ClassicMovies { get; set; }
        public int[] ClassicMusicals { get; set; }
        public int[] ClassicRampBSoul { get; set; }
        public int[] ClassicRomanticMovies { get; set; }
        public int[] ClassicSciFiampFantasy { get; set; }
        public int[] ClassicThrillers { get; set; }
        public int[] ClassicTVShows { get; set; }
        public int[] ClassicWarMovies { get; set; }
        public int[] ClassicWesterns { get; set; }
        public int[] ClassicalMusic { get; set; }
        public int[] ColombianMovies { get; set; }
        public int[] Comedies { get; set; }
        public int[] ComedyJams { get; set; }
        public int[] ComicBookampSuperheroTV { get; set; }
        public int[] ComicBookandSuperheroMovies { get; set; }
        public int[] CompetitionRealityTV { get; set; }
        public int[] ContemporaryRampB { get; set; }
        public int[] CountryampWesternFolk { get; set; }
        public int[] CourtroomDramas { get; set; }
        public int[] CourtroomTVDramas { get; set; }
        public int[] CreatureFeatures { get; set; }
        public int[] CrimeAction { get; set; }
        public int[] CrimeActionampAdventure { get; set; }
        public int[] CrimeComedies { get; set; }
        public int[] CrimeDocumentaries { get; set; }
        public int[] CrimeDramas { get; set; }
        public int[] CrimeFilms { get; set; }
        public int[] CrimeFilmsbasedonreallife { get; set; }
        public int[] CrimeThrillers { get; set; }
        public int[] CrimeTVDocumentaries { get; set; }
        public int[] CrimeTVDramas { get; set; }
        public int[] CrimeTVShows { get; set; }
        public int[] CrimeTVSoaps { get; set; }
        public int[] CriticallyacclaimedActionampAdventure { get; set; }
        public int[] CriticallyacclaimedComedies { get; set; }
        public int[] CriticallyacclaimedDramas { get; set; }
        public int[] CriticallyacclaimedFilms { get; set; }
        public int[] CriticallyacclaimedIndependentFilms { get; set; }
        public int[] CriticallyacclaimedSciFiampFantasy { get; set; }
        public int[] CultComedies { get; set; }
        public int[] CultHorrorMovies { get; set; }
        public int[] CultMovies { get; set; }
        public int[] CultSciFiampFantasy { get; set; }
        public int[] CultTVShows { get; set; }
        public int[] Dance { get; set; }
        public int[] DanceampElectronica { get; set; }
        public int[] DanishComedies { get; set; }
        public int[] DanishCrimeMovies { get; set; }
        public int[] DanishDocumentaries { get; set; }
        public int[] DanishDramas { get; set; }
        public int[] DanishFilms { get; set; }
        public int[] DanishTVShows { get; set; }
        public int[] DarkComedies { get; set; }
        public int[] DeepSeaHorrorMovies { get; set; }
        public int[] Disco { get; set; }
        public int[] Disney { get; set; }
        public int[] DisneyMusicals { get; set; }
        public int[] Documentaries { get; set; }
        public int[] Dramas { get; set; }
        public int[] DramasbasedonBooks { get; set; }
        public int[] Dramasbasedonclassicliterature { get; set; }
        public int[] Dramasbasedoncontemporaryliterature { get; set; }
        public int[] Dramasbasedonreallife { get; set; }
        public int[] DutchChildrenampFamilyMovies { get; set; }
        public int[] DutchComedies { get; set; }
        public int[] DutchDramas { get; set; }
        public int[] DutchKidsTV { get; set; }
        public int[] DutchMovies { get; set; }
        public int[] DutchTVShows { get; set; }
        public int[] EasternEuropeanMovies { get; set; }
        public int[] EducationforKids { get; set; }
        public int[] Epics { get; set; }
        public int[] EuropeanMovies { get; set; }
        public int[] ExperimentalMovies { get; set; }
        public int[] FaithampSpirituality { get; set; }
        public int[] FaithampSpiritualityMovies { get; set; }
        public int[] FamilyAdventures { get; set; }
        public int[] FamilyAnimation { get; set; }
        public int[] FamilyComedies { get; set; }
        public int[] FamilyDramas { get; set; }
        public int[] FamilyFeatureAnimation { get; set; }
        public int[] FamilyFeatures { get; set; }
        public int[] FamilySciFiampFantasy { get; set; }
        public int[] FantasyMovies { get; set; }
        public int[] FemaleStandupComedy { get; set; }
        public int[] FilmNoir { get; set; }
        public int[] FinnishMovies { get; set; }
        public int[] FinnishTVShows { get; set; }
        public int[] FoodampTravelTV { get; set; }
        public int[] FoodampWine { get; set; }
        public int[] FootballMovies { get; set; }
        public int[] ForeignActionampAdventure { get; set; }
        public int[] ForeignComedies { get; set; }
        public int[] ForeignDocumentaries { get; set; }
        public int[] ForeignDramas { get; set; }
        public int[] ForeignGayampLesbianMovies { get; set; }
        public int[] ForeignHorrorMovies { get; set; }
        public int[] ForeignMovies { get; set; }
        public int[] ForeignSciFiampFantasy { get; set; }
        public int[] ForeignThrillers { get; set; }
        public int[] FrenchComedies { get; set; }
        public int[] FrenchDocumentaries { get; set; }
        public int[] FrenchDramas { get; set; }
        public int[] FrenchMovies { get; set; }
        public int[] FrenchThrillers { get; set; }
        public int[] GangsterMovies { get; set; }
        public int[] GayampLesbianComedies { get; set; }
        public int[] GayampLesbianDocumentaries { get; set; }
        public int[] GayampLesbianDramas { get; set; }
        public int[] GayampLesbianMovies { get; set; }
        public int[] GayampLesbianTVShows { get; set; }
        public int[] GermanComedies { get; set; }
        public int[] GermanDramas { get; set; }
        public int[] GermanMovies { get; set; }
        public int[] GermanTVShows { get; set; }
        public int[] GoldenGlobeAwardwinningFilms { get; set; }
        public int[] GoryHalloweenFavorites { get; set; }
        public int[] GospelMusic { get; set; }
        public int[] GreekMovies { get; set; }
        public int[] HalloweenFavorites { get; set; }
        public int[] HalloweenFavourites { get; set; }
        public int[] HardRockampHeavyMetal { get; set; }
        public int[] HeistFilms { get; set; }
        public int[] HistoricalDocumentaries { get; set; }
        public int[] HistoricalDramas { get; set; }
        public int[] HolidayFavorites { get; set; }
        public int[] HolidayFun { get; set; }
        public int[] HorrorComedy { get; set; }
        public int[] HorrorMovies { get; set; }
        public int[] IndependentActionampAdventure { get; set; }
        public int[] IndependentComedies { get; set; }
        public int[] IndependentDramas { get; set; }
        public int[] IndependentMovies { get; set; }
        public int[] IndependentThrillers { get; set; }
        public int[] IndianComedies { get; set; }
        public int[] IndianDramas { get; set; }
        public int[] IndianMovies { get; set; }
        public int[] InspirationalMusic { get; set; }
        public int[] InternationalActionampAdventure { get; set; }
        public int[] InternationalComedies { get; set; }
        public int[] InternationalDocumentaries { get; set; }
        public int[] InternationalDramas { get; set; }
        public int[] InternationalKidsTV { get; set; }
        public int[] InternationalMovies { get; set; }
        public int[] InternationalSciFiampFantasy { get; set; }
        public int[] InternationalThrillers { get; set; }
        public int[] InternationalTVActionampAdventure { get; set; }
        public int[] InternationalTVComedies { get; set; }
        public int[] InternationalTVDramas { get; set; }
        public int[] InternationalTVShows { get; set; }
        public int[] InvestigativeRealityTV { get; set; }
        public int[] IrishMovies { get; set; }
        public int[] ItalianComedies { get; set; }
        public int[] ItalianDramas { get; set; }
        public int[] ItalianMovies { get; set; }
        public int[] ItalianThrillers { get; set; }
        public int[] JapaneseAcademyAwardwinningMovies { get; set; }
        public int[] JapaneseActionampAdventure { get; set; }
        public int[] JapaneseComedies { get; set; }
        public int[] JapaneseDramas { get; set; }
        public int[] JapaneseHorrorMovies { get; set; }
        public int[] JapaneseKidsTV { get; set; }
        public int[] JapaneseMovies { get; set; }
        public int[] JapanesePeriodDramas { get; set; }
        public int[] JapaneseSciFiampFantasy { get; set; }
        public int[] JapaneseThrillers { get; set; }
        public int[] JapaneseTVComedies { get; set; }
        public int[] JapaneseTVDramas { get; set; }
        public int[] JapaneseTVFilms { get; set; }
        public int[] JapaneseTVSciFiampFantasy { get; set; }
        public int[] JapaneseTVShows { get; set; }
        public int[] JapaneseTVThrillers { get; set; }
        public int[] JazzampEasyListening { get; set; }
        public int[] KidsAnime { get; set; }
        public int[] KidsFaithampSpirituality { get; set; }
        public int[] KidsMusic { get; set; }
        public int[] KidsTVforages0to2 { get; set; }
        public int[] KidsTVforages11to12 { get; set; }
        public int[] KidsTVforages2to4 { get; set; }
        public int[] KidsTVforages5to7 { get; set; }
        public int[] KidsTVforages8to10 { get; set; }
        public int[] Kidsamp39TV { get; set; }
        public int[] KoreanActionampAdventure { get; set; }
        public int[] KoreanComedies { get; set; }
        public int[] KoreanDramas { get; set; }
        public int[] KoreanMovies { get; set; }
        public int[] KoreanThrillers { get; set; }
        public int[] KoreanTVDramas { get; set; }
        public int[] KoreanTVShows { get; set; }
        public int[] LateNightComedies { get; set; }
        public int[] LatinAmericanComedies { get; set; }
        public int[] LatinAmericanDocumentaries { get; set; }
        public int[] LatinAmericanDramas { get; set; }
        public int[] LatinAmericanMovies { get; set; }
        public int[] LatinAmericanMusicampMusicals { get; set; }
        public int[] LatinAmericanPoliceTVShows { get; set; }
        public int[] LatinAmericanTVShows { get; set; }
        public int[] LatinMusic { get; set; }
        public int[] LatinoStandupComedy { get; set; }
        public int[] LaughOutLoudComedies { get; set; }
        public int[] MartialArtsMovies { get; set; }
        public int[] MartialArtsBoxingampWrestling { get; set; }
        public int[] MedicalTVDramas { get; set; }
        public int[] MexicanComedies { get; set; }
        public int[] MexicanDramas { get; set; }
        public int[] MexicanFilms { get; set; }
        public int[] MexicanTVShows { get; set; }
        public int[] MiddleEasternMovies { get; set; }
        public int[] MilitaryampWarActionampAdventure { get; set; }
        public int[] MilitaryampWarDocumentaries { get; set; }
        public int[] MilitaryampWarDramas { get; set; }
        public int[] MilitaryampWarMovies { get; set; }
        public int[] MilitaryActionampAdventure { get; set; }
        public int[] MilitaryDocumentaries { get; set; }
        public int[] MilitaryDramas { get; set; }
        public int[] MilitaryTVShows { get; set; }
        public int[] Miniseries { get; set; }
        public int[] Mockumentaries { get; set; }
        public int[] ModernampAlternativeRock { get; set; }
        public int[] ModernClassicMovies { get; set; }
        public int[] MonsterMovies { get; set; }
        public int[] Moviesbasedonchildrenamp39sbooks { get; set; }
        public int[] Moviesforages0to2 { get; set; }
        public int[] Moviesforages11to12 { get; set; }
        public int[] Moviesforages2to4 { get; set; }
        public int[] Moviesforages5to7 { get; set; }
        public int[] Moviesforages8to10 { get; set; }
        public int[] Music { get; set; }
        public int[] MusicampConcertDocumentaries { get; set; }
        public int[] MusicampMusicals { get; set; }
        public int[] MusicandConcertFilms { get; set; }
        public int[] Musicals { get; set; }
        public int[] Mysteries { get; set; }
        public int[] NatureampEcologyDocumentaries { get; set; }
        public int[] NatureampEcologyTVDocumentaries { get; set; }
        public int[] NewCountry { get; set; }
        public int[] NewZealandMovies { get; set; }
        public int[] NollywoodMovies { get; set; }
        public int[] NordicChildrenampFamilyMovies { get; set; }
        public int[] NordicComedies { get; set; }
        public int[] NordicCrimeMovies { get; set; }
        public int[] NordicDramas { get; set; }
        public int[] NordicThrillers { get; set; }
        public int[] NordicTVShows { get; set; }
        public int[] NorwegianComedies { get; set; }
        public int[] NorwegianCrimeMovies { get; set; }
        public int[] NorwegianDramas { get; set; }
        public int[] NorwegianFilms { get; set; }
        public int[] NorwegianThrillers { get; set; }
        public int[] NorwegianTV { get; set; }
        public int[] PeriodPieces { get; set; }
        public int[] PoliceActionampAdventure { get; set; }
        public int[] PoliceDetectiveMovies { get; set; }
        public int[] PoliceDramas { get; set; }
        public int[] PoliceMovies { get; set; }
        public int[] PoliceMysteries { get; set; }
        public int[] PoliceThrillers { get; set; }
        public int[] PoliceTVShows { get; set; }
        public int[] PoliticalComedies { get; set; }
        public int[] PoliticalDocumentaries { get; set; }
        public int[] PoliticalDramas { get; set; }
        public int[] PoliticalThrillers { get; set; }
        public int[] PoliticalTVDocumentaries { get; set; }
        public int[] Pop { get; set; }
        public int[] PsychologicalThrillers { get; set; }
        public int[] PunkRock { get; set; }
        public int[] QuirkyRomance { get; set; }
        public int[] RapampHipHop { get; set; }
        public int[] RealityTV { get; set; }
        public int[] Reggae { get; set; }
        public int[] ReligiousDocumentaries { get; set; }
        public int[] RetroAnime { get; set; }
        public int[] RockampPopConcerts { get; set; }
        public int[] Rockumentaries { get; set; }
        public int[] RomanticComedies { get; set; }
        public int[] RomanticDanishMovies { get; set; }
        public int[] RomanticDramas { get; set; }
        public int[] RomanticFavorites { get; set; }
        public int[] RomanticFilmsbasedonabook { get; set; }
        public int[] RomanticForeignMovies { get; set; }
        public int[] RomanticGayampLesbianMovies { get; set; }
        public int[] RomanticIndependentMovies { get; set; }
        public int[] RomanticJapaneseFilms { get; set; }
        public int[] RomanticJapaneseMovies { get; set; }
        public int[] RomanticJapaneseTVShows { get; set; }
        public int[] RomanticMovies { get; set; }
        public int[] RomanticMoviesbasedonBooks { get; set; }
        public int[] RomanticNordicMovies { get; set; }
        public int[] RomanticSwedishMovies { get; set; }
        public int[] RomanticTVProgrammes { get; set; }
        public int[] RomanticTVSoaps { get; set; }
        public int[] Russian { get; set; }
        public int[] SatanicStories { get; set; }
        public int[] Satires { get; set; }
        public int[] ScandinavianComedies { get; set; }
        public int[] ScandinavianCrimeFilms { get; set; }
        public int[] ScandinavianDocumentaries { get; set; }
        public int[] ScandinavianDramas { get; set; }
        public int[] ScandinavianIndependentMovies { get; set; }
        public int[] ScandinavianMovies { get; set; }
        public int[] ScandinavianThrillers { get; set; }
        public int[] ScandinavianTV { get; set; }
        public int[] SciFi { get; set; }
        public int[] SciFiampFantasy { get; set; }
        public int[] SciFiAdventure { get; set; }
        public int[] SciFiDramas { get; set; }
        public int[] SciFiHorrorMovies { get; set; }
        public int[] SciFiThrillers { get; set; }
        public int[] ScienceampNatureDocumentaries { get; set; }
        public int[] ScienceampNatureTV { get; set; }
        public int[] ScienceampTechnologyDocumentaries { get; set; }
        public int[] ScienceampTechnologyTVDocumentaries { get; set; }
        public int[] ScrewballComedies { get; set; }
        public int[] ShowbizDramas { get; set; }
        public int[] ShowbizMusicals { get; set; }
        public int[] SilentMovies { get; set; }
        public int[] SingerSongwriters { get; set; }
        public int[] Sitcoms { get; set; }
        public int[] SlapstickComedies { get; set; }
        public int[] SlasherandSerialKillerMovies { get; set; }
        public int[] SliceofLifeAnime { get; set; }
        public int[] SoccerMovies { get; set; }
        public int[] SoccerNonfiction { get; set; }
        public int[] SocialampCulturalDocumentaries { get; set; }
        public int[] SocialIssueDramas { get; set; }
        public int[] SoutheastAsianMovies { get; set; }
        public int[] SpanishComedies { get; set; }
        public int[] SpanishDramas { get; set; }
        public int[] SpanishHorrorFilms { get; set; }
        public int[] SpanishHorrorMovies { get; set; }
        public int[] SpanishMovies { get; set; }
        public int[] SpanishThrillers { get; set; }
        public int[] SpanishLanguageTVShows { get; set; }
        public int[] SpecialInterest { get; set; }
        public int[] SpiritualDocumentaries { get; set; }
        public int[] SportsampFitness { get; set; }
        public int[] SportsComedies { get; set; }
        public int[] SportsDocumentaries { get; set; }
        public int[] SportsDramas { get; set; }
        public int[] SportsMovies { get; set; }
        public int[] SportsTVProgrammes { get; set; }
        public int[] SpyActionampAdventure { get; set; }
        public int[] SpyThrillers { get; set; }
        public int[] StageMusicals { get; set; }
        public int[] StandupComedy { get; set; }
        public int[] SteamyRomance { get; set; }
        public int[] SteamyRomanticMovies { get; set; }
        public int[] SteamyThrillers { get; set; }
        public int[] SupernaturalHorrorMovies { get; set; }
        public int[] SupernaturalThrillers { get; set; }
        public int[] SwedishComedies { get; set; }
        public int[] SwedishCrimeMovies { get; set; }
        public int[] SwedishFilms { get; set; }
        public int[] SwedishTVShows { get; set; }
        public int[] TalkShowsampStandupComedy { get; set; }
        public int[] Tearjerkers { get; set; }
        public int[] TeenComedies { get; set; }
        public int[] TeenDramas { get; set; }
        public int[] TeenRomance { get; set; }
        public int[] TeenScreams { get; set; }
        public int[] TeenTVShows { get; set; }
        public int[] TheatreArts { get; set; }
        public int[] Thrillers { get; set; }
        public int[] TravelampAdventureDocumentaries { get; set; }
        public int[] TravelampAdventureRealityTV { get; set; }
        public int[] TVActionampAdventure { get; set; }
        public int[] TVAnimatedComedies { get; set; }
        public int[] TVCartoons { get; set; }
        public int[] TVComedies { get; set; }
        public int[] TVComedyDramas { get; set; }
        public int[] TVDocumentariesa { get; set; }
        public int[] TVDramas { get; set; }
        public int[] TVHorror { get; set; }
        public int[] TVMysteries { get; set; }
        public int[] TVSciFiampFantasy { get; set; }
        public int[] TVShows { get; set; }
        public int[] TVSketchComedies { get; set; }
        public int[] TVSoaps { get; set; }
        public int[] TVSoapsFeaturingaStrongFemaleLead { get; set; }
        public int[] TVTeenDramas { get; set; }
        public int[] TVThrillers { get; set; }
        public int[] TVWesterns { get; set; }
        public int[] UrbanampDanceConcerts { get; set; }
        public int[] USMovies { get; set; }
        public int[] USPoliceTVShows { get; set; }
        public int[] USTVComedies { get; set; }
        public int[] USTVDocumentaries { get; set; }
        public int[] USTVDramas { get; set; }
        public int[] USTVProgrammes { get; set; }
        public int[] VampireFilms { get; set; }
        public int[] VampireHorrorMovies { get; set; }
        public int[] VocalJazz { get; set; }
        public int[] VocalPop { get; set; }
        public int[] WackyComedies { get; set; }
        public int[] WerewolfHorrorMovies { get; set; }
        public int[] Westerns { get; set; }
        public int[] WineampBeverageAppreciation { get; set; }
        public int[] WorldMusicConcerts { get; set; }
        public int[] WWIIFilms { get; set; }
        public int[] ZombieHorrorMovies { get; set; }
        public int[] x56FDx5185TVx30C9x30E9x30DE { get; set; }
        public int[] x56FDx5185TVx756Ax7D44x30FBx30C9x30E9x30DE { get; set; }
        public int[] x56FDx5185x30C9x30E9x30DE { get; set; }
    }
}
